COMPONENT= TemperatureC
CFLAGS += -I$(TOSDIR)/lib/printf \
          -I$(TOSROOT)/apps/IDS/lib/ \
          -I$(TOSDIR)/lib/net \
          -I$(TOSDIR)/lib/net/4bitle \
          -I$(TOSDIR)/lib/net/ctp 

include $(MAKERULES)
